// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydqdrA6v7xBBPjF6geRWxbiFsfnG581A',
    appId: '1:396163404110:web:eee735afe47474a00a4e1f',
    messagingSenderId: '396163404110',
    projectId: 'projectga-d3f20',
    authDomain: 'projectga-d3f20.firebaseapp.com',
    databaseURL: 'https://projectga-d3f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectga-d3f20.firebasestorage.app',
    measurementId: 'G-TTGBWRZ188',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtZZTRev5RrXYtoJRmsdZ2AffuVzairVk',
    appId: '1:396163404110:android:4e0f4ebad6988bee0a4e1f',
    messagingSenderId: '396163404110',
    projectId: 'projectga-d3f20',
    databaseURL: 'https://projectga-d3f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectga-d3f20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWh4vX1z7VDEj81PiIFbc0eeZECYwsdI',
    appId: '1:396163404110:ios:984cf63ae74796c20a4e1f',
    messagingSenderId: '396163404110',
    projectId: 'projectga-d3f20',
    databaseURL: 'https://projectga-d3f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectga-d3f20.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppGa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYWh4vX1z7VDEj81PiIFbc0eeZECYwsdI',
    appId: '1:396163404110:ios:984cf63ae74796c20a4e1f',
    messagingSenderId: '396163404110',
    projectId: 'projectga-d3f20',
    databaseURL: 'https://projectga-d3f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectga-d3f20.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppGa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAydqdrA6v7xBBPjF6geRWxbiFsfnG581A',
    appId: '1:396163404110:web:b0577601a70eba040a4e1f',
    messagingSenderId: '396163404110',
    projectId: 'projectga-d3f20',
    authDomain: 'projectga-d3f20.firebaseapp.com',
    databaseURL: 'https://projectga-d3f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectga-d3f20.firebasestorage.app',
    measurementId: 'G-RB2RNYRQR6',
  );
}
